"""Add is_admin field to User model

Revision ID: 504f6ccba30e
Revises: c38ee20fcc9e
Create Date: 2025-02-12 13:17:38.251875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504f6ccba30e'
down_revision = 'c38ee20fcc9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_groups',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    info={'bind_key': None}
    )
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_index('ix_user_email', table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.drop_column('user', 'is_admin')
    op.drop_table('user_groups')
    op.drop_table('group')
    # ### end Alembic commands ###
