"""Add urgency to File model

Revision ID: ef64f24ba2bb
Revises: 504f6ccba30e
Create Date: 2025-02-13 13:48:39.911179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef64f24ba2bb'
down_revision = '504f6ccba30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('urgency', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'urgency')
    # ### end Alembic commands ###
